name: Build Release


on:
  push:
    branches:
      - main


permissions:
  contents: write


jobs:
  Get-Game-Version:
    runs-on: windows-latest
    
    outputs:
      game-version: ${{ steps.game-version.outputs.version }}

    steps:
      - name: Getting the GitHub repository
        uses: actions/checkout@v6
      
      - name: Getting the game version
        id: game-version
        shell: pwsh
        run: |
          $gamePropertiesFilePath = "ProjectFiles\Shared\Constants\GameProperties.cs"

          $fileContent = Get-Content $gamePropertiesFilePath -Raw

          if ($fileContent -notmatch 'GAME_VERSION\s*=\s*"([^"]+)"')
          {
            Write-Error "ERROR: [Build_Release] Unable to retrieve GAME_VERSION from [$gamePropertiesFilePath]."
            exit 1
          }

          $gameVersion = $Matches[1]

          Write-Host "Game version: $gameVersion"

          "version=$gameVersion" >> $env:GITHUB_OUTPUT


          
  Build-BackEnd:
    runs-on: windows-latest

    steps:
      - name: Getting the GitHub repository
        uses: actions/checkout@v6
      
      - name: Installing .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      - name: Publishing the BackEnd
        shell: pwsh
        run: |
          dotnet publish `
            ProjectFiles\BackEnd\GaucheOuDroiteBackEnd\GaucheOuDroiteBackEnd.csproj `
            --configuration Release `
            -p:PublishProfile=FolderProfile `
            -p:PublishDir="$PWD\Build\Server"
        # Doing "-p:PublishDir="$PWD\Build\Server" is equivalent of "doing --output Build\Server", we just use the "FolderProfile.pubxml"
              
      - name: Setting the JWT key
        env:
          JWT_KEY: ${{ secrets.JWT_KEY }}
        shell: pwsh
        run: |
          $configPath = "Build\Server\appsettings.Production.json"
        
          $config = Get-Content $configPath -Raw | ConvertFrom-Json
        
          $config.JwtSettings.Key = $env:JWT_KEY
        
          $config | ConvertTo-Json -Depth 10 | Set-Content $configPath
        
      - name: Uploading the BackEnd build
        uses: actions/upload-artifact@v7
        with:
          name: BackEnd-Build
          path: Build\Server



  Build-FrontEnd:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - language: FRA
            branch: main

          - language: ENG
            branch: feat-EnglishVersion
  
    steps:
      - name: Getting the GitHub repository
        uses: actions/checkout@v6
        with:
          ref: ${{ matrix.branch }}

      - name: Caching Unity Library
        uses: actions/cache@v6
        with:
          path: ProjectFiles/FrontEnd/GaucheOuDroite/Library
          key: Library-GaucheOuDroite-StandaloneWindows64-${{ matrix.language }}
          restore-keys: |
            Library-GaucheOuDroite-StandaloneWindows64-
            Library-GaucheOuDroite-
            Library-

      - name: Building the Unity project
        uses: game-ci/unity-builder@v6
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL_ADRESS }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ProjectFiles/FrontEnd/GaucheOuDroite
          unityVersion: 6000.3.16f1
          targetPlatform: StandaloneWindows64
          buildsPath: Build
          buildName: GaucheOuDroite

      - name: Uploading the FrontEnd build
        uses: actions/upload-artifact@v7
        with:
          name: FrontEnd-Build_${{ matrix.language }}
          path: Build/StandaloneWindows64
          


  Zip-Builds:
    needs: [Get-Game-Version, Build-BackEnd, Build-FrontEnd]

    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - language: FRA
            front-end-artifact: FrontEnd-Build_FRA
            instructions-file-name: Instructions d'utilisation.txt
            instructions-file-content: |
              Afin de jouer au jeu, il vous faut lancer les exécutables suivants :

              - "GaucheOuDroite_Server.exe" (dans le dossier "Server")
              - "GaucheOuDroite.exe" (dans le dossier "Client")

          - language: ENG
            front-end-artifact: FrontEnd-Build_ENG
            instructions-file-name: Instructions for use.txt
            instructions-file-content: |
              To play the game, you need to run the following executables:

              - "GaucheOuDroite_Server.exe" (in "Server" folder)
              - "GaucheOuDroite.exe" (in "Client" folder)

    steps:
      - name: Downloading the BackEnd build
        uses: actions/download-artifact@v7
        with:
          name: BackEnd-Build
          path: Build\BackEnd

      - name: Downloading the FrontEnd build
        uses: actions/download-artifact@v7
        with:
          name: ${{ matrix.front-end-artifact }}
          path: Build\FrontEnd

      - name: Creating the release directory
        shell: pwsh
        run: |
          $gameVersion = "${{ needs.Get-Game-Version.outputs.game-version }}"

          $releaseDirectory = "Build\GaucheOuDroite-Build-${gameVersion}_${{ matrix.language }}"

          New-Item -ItemType Directory -Path "$releaseDirectory\Client" -Force
          New-Item -ItemType Directory -Path "$releaseDirectory\Server" -Force

          Copy-Item "Build\FrontEnd\*" "$releaseDirectory\Client" -Recurse -Force
          Copy-Item "Build\BackEnd\*" "$releaseDirectory\Server" -Recurse -Force

          @"
          ${{ matrix.instructions-file-content }}
          "@ | Set-Content "$releaseDirectory\${{ matrix.instructions-file-name }}" -Encoding UTF8

      # Commented because that would create a .zip inside a .zip, "Uploading the Builds" already zip the files.
      #- name: Creating the ZIP
      #  shell: pwsh
      #  run: |
      #    $gameVersion = "${{ needs.Get-Game-Version.outputs.game-version }}"
      #
      #    $releaseDirectory = "Build\GaucheOuDroite-Build-${gameVersion}_${{ matrix.language }}"
      #    $zipPath = "Build\GaucheOuDroite-Build-${gameVersion}_${{ matrix.language }}.zip"
      #
      #    Compress-Archive `
      #      -Path $releaseDirectory `
      #      -DestinationPath $zipPath `
      #      -Force

      - name: Uploading the Builds
        uses: actions/upload-artifact@v7
        with:
          name: GaucheOuDroite-Build-${{ needs.Get-Game-Version.outputs.game-version }}_${{ matrix.language }}
          path: Build/GaucheOuDroite-Build-${{ needs.Get-Game-Version.outputs.game-version }}_${{ matrix.language }}



  Create-GitHub-Release:
    needs: [Get-Game-Version, Zip-Builds]

    runs-on: windows-latest

    steps:
      - name: Getting the GitHub repository
        uses: actions/checkout@v6

      - name: Downloading the French Build
        uses: actions/download-artifact@v8
        with:
          name: GaucheOuDroite-Build-${{ needs.Get-Game-Version.outputs.game-version }}_FRA
          path: Build
          skip-decompress: true

      - name: Downloading the English Build
        uses: actions/download-artifact@v8
        with:
          name: GaucheOuDroite-Build-${{ needs.Get-Game-Version.outputs.game-version }}_ENG
          path: Build
          skip-decompress: true

      - name: Creating the GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          $gameVersion = "${{ needs.Get-Game-Version.outputs.game-version }}"
          $tag = "v$gameVersion"

          $owner = "${{ github.repository_owner }}"
          $repository = "${{ github.event.repository.name }}"

          #
          # Generating the automatic GitHub Release Notes
          #

          $generateNotesBody = @{
            tag_name = $tag
            target_commitish = "${{ github.sha }}"
          } | ConvertTo-Json

          $generatedNotesResponse = gh api `
            --method POST `
            "repos/$owner/$repository/releases/generate-notes" `
            --input - `
            <<< $generateNotesBody

      - name: Creating the GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          $gameVersion = "${{ needs.Get-Game-Version.outputs.game-version }}"
          $tag = "v$gameVersion"

          $notes = @"
          # This Release contains all the Build files for version $gameVersion.

          This includes the FrontEnd (Client) and the BackEnd (Server).

          ### The main point of version $gameVersion is ***[TODO: Add the main point of this version]***

          ### Things added / modified:

          ---

          ***TODO: Add the things added / modified]***

          ---

          ## To play the game:

          - unzip the files
          - start the GaucheOuDroite_Server.exe
          - start the GaucheOuDroite.exe
          - have fun :D

          In the files, there is a small .txt file.
          If you have forgotten how to launch the game and can't be bothered to come back here, you can read it.

          > [!NOTE]
          > The server is only running locally on your computer.
          > So even if you create an account using one of your real passwords, I wouldn't know anything about it.

          ---

          ### You can download the French and English Builds below this release.
          "@

          $notesFile = "Build\ReleaseNotes.md"
          $notes | Set-Content $notesFile -Encoding UTF8

          gh release create "$tag" `
            "Build\GaucheOuDroite-Build-${gameVersion}_FRA.zip" `
            "Build\GaucheOuDroite-Build-${gameVersion}_ENG.zip" `
            --title "Project release v$gameVersion" `
            --notes-file "$notesFile" `
            --generate-notes `
            --fail-on-no-commits `
            --target "${{ github.sha }}"