name: Build Release


on:
  push:
    branches:
      - main


jobs:
  Build-BackEnd:
    runs-on: windows-latest
    
    steps:
      - name: Getting the GitHub repository
        uses: actions/checkout@v6
      
      - name: Installing .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
      
      - name: Publishing the BackEnd
        run: dotnet publish ProjectFiles\BackEnd\GaucheOuDroiteBackEnd\GaucheOuDroiteBackEnd.csproj --configuration Release --output Build\Server
              
      - name: Setting the JWT key
        env:
          JWT_KEY: ${{ secrets.JWT_KEY }}
        shell: pwsh
        run: |
          $configPath = "Build\Server\appsettings.Production.json"
        
          $config = Get-Content $configPath -Raw | ConvertFrom-Json
        
          $config.JwtSettings.Key = $env:JWT_KEY
        
          $config | ConvertTo-Json -Depth 10 | Set-Content $configPath
        
      - name: Uploading the BackEnd build
        uses: actions/upload-artifact@v6
        with:
          name: BackEnd-Build
          path: Build\Server


  Build-FrontEnd_FRA:
    runs-on: ubuntu-latest
  
    steps:
      - name: Getting the GitHub repository
        uses: actions/checkout@v6

      - name: Caching Unity Library
        uses: actions/cache@v6
        with:
          path: ProjectFiles/FrontEnd/GaucheOuDroite/Library
          key: Library-GaucheOuDroite-StandaloneWindows64
          restore-keys: |
            Library-GaucheOuDroite-
            Library-
    
      - name: Building the Unity project
        uses: game-ci/unity-builder@v6
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL_ADRESS }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ProjectFiles/FrontEnd/GaucheOuDroite
          unityVersion: 6000.3.16f1
          targetPlatform: StandaloneWindows64
          buildsPath: Build
          buildName: Client
        
      - name: Uploading the FrontEnd build
        uses: actions/upload-artifact@v6
        with:
          name: FrontEnd-Build_FRA
          path: Build/Client # We use the / and not the \ because we are on Ubuntu not Windows
#
#
#  Zip-Builds_FRA: # TODO
#    needs: [Build-FrontEnd_FRA, Build-BackEnd]
#    runs-on: windows-latest
#    
#    steps:
#      - name: Getting the GitHub repository
#        uses: actions/checkout@v6
#
#
#  Zip-Builds_ENG: # TODO
#    needs: [Build-FrontEnd_ENG, Build-BackEnd]
#    runs-on: windows-latest
#    
#    steps:
#      - name: Getting the GitHub repository
#        uses: actions/checkout@v6
#      
#
#  Create-Release: # TODO
#    needs: [Zip-Builds_FRA, Zip-Builds_ENG]
#    runs-on: windows-latest
#    
#    steps:
#      - name: Getting the GitHub repository
#        uses: actions/checkout@v6